### ISSUE TITLE
can't configure it :(

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/integration_twitter#1]
I tried to get it to work on our tech preview server (roeland can probably get you logs or, if needed, root access).

All I find in the Nc log:
Undefined variable: result at /var/www/tech-preview.nextcloud.com/apps/integration_twitter/lib/Controller/TwitterAPIController.php#71

Screenshot:
![Screenshot_20200904_184155](https://user-images.githubusercontent.com/551757/92267004-79b1c580-eee0-11ea-9e76-2c774eca0483.png)

**Comment by eneiluj** [comment]
I'll fix the Php warning. It is not the reason why it does not work for you.

Did you get the registration popup/dialog when loading the linked settings page?

What browser are you using? Is it compatible with protocol registration?

Could you try with Firefox or Chromium?

**Comment by eneiluj** [comment]
I tried again with Chromium and Firefox, fresh configs, works fine.

So your problem is that your browser does not understand the "web+nextcloudtwitter://" protocol. I can think of 2 reasons for that:
* this protocol was not registered when loading linked accounts settings page
* your browser is not compatible with such protocol

**Comment by ChristophWurst** [comment]
https://sentry.io/share/issue/50b596d7b5484a479de70cbd0d2ce9b7/

**Comment by ChristophWurst** [comment]
> So your problem is that your browser does not understand the "web+nextcloudtwitter://" protocol.

Ignorant me didn't click the button when the browser asked because I thought I don't care about this. Is this the only way to handle the oauth flow or could we also have a real route Twitter redirects the user back to?

On a side note the oauth page of twitter shows `github.com/nextcloud/twitter` as URL. We should either move the repo or change the URL, I'm afraid this is against their ToS.

**Comment by eneiluj** [comment]
The Php error has been fixed. It's not related with @jospoortvliet 's OAuth problem.

@ChristophWurst So did you manage to get access to your Twitter account?

> could we also have a real route Twitter redirects the user back to

The problem with that approach is that the redirect URL has to be declared in the Twitter OAuth app. We can't declare every Nextcloud redirection URLs in our Twitter OAuth app :grin:. So it means each Nextcloud admin would have to create a Twitter app which is a long process (took me 3 weeks to get a dev account).

Using a protocol-based redirect allows us to make one single Twitter OAuth app used by every Nextcloud instances.

Am I missing a magical way to make it work with HTTPS redirection URLs?

**Comment by ChristophWurst** [comment]
> @ChristophWurst So did you manage to get access to your Twitter account?

Yes, the second time I added the URL handler, then it was smooth :)



> The problem with that approach is that the redirect URL has to be declared in the Twitter OAuth app. We can't declare every Nextcloud redirection URLs in our Twitter OAuth app grin. So it means each Nextcloud admin would have to create a Twitter app which is a long process (took me 3 weeks to get a dev account).

Got it. I though you could send the URL with each oauth request.

**Comment by eneiluj** [comment]
@ChristophWurst 
> Got it. I though you could send the URL with each oauth request.

You can but it needs to be listed as accepted on the Twitter side (of the force).

**Comment by eneiluj** [comment]
@ChristophWurst Thanks for the feedback btw!

**Comment by Ludovicis** [comment]
On Chrome Version 85.0.4183.121 (Build officiel) (64 bits) i have not this pop-up
![image](https://user-images.githubusercontent.com/16205280/94920758-2f0f7300-04b7-11eb-9cda-c2dd7c12ac45.png)

On Firefox 81.0 (64 bits), yes

**Comment by eneiluj** [comment]
@Ludovicis Are you sure you registered the protocol when loading the page in Chrome?

Could you check in chrome://settings/handlers page (accessed with Chrome :grin:) if something is registered or blocked for `web+nextcloudtwitter` protocol?

**Comment by eneiluj** [comment]
@Ludovicis Also, did you check if this icon
![chromium](https://user-images.githubusercontent.com/11291457/94921992-ad6d1480-04b9-11eb-80a9-0bee78dddb24.png)
was visible when you browser the connected accounts personal settings page?

**Comment by Ludovicis** [comment]
@Eneilu
you're right, i hadn't paid attention sorry. It works by authorizing from the icon in the address bar on Chrome

**Comment by eneiluj** [comment]
Yeah well we can still complain about Chrome-ium making this harder than on Firefox.

Thanks to your remark, I added one more hint about the chrome:// protocol handler settings.

Cheers
