### ISSUE TITLE
App unpublished for Nextcloud 20

### ISSUE THREAD

**Issue by aszlig** [nextcloud/integration_twitter#10]
Got the app removal via my custom updater and indeed, the app is [no longer available for Nextcloud 20](https://apps.nextcloud.com/apps/integration_twitter).

I waited with the removal for my project for a few days to see whether this would be fixed along with the other `integration_*` apps, but it doesn't seem to be the case.

Is this intentional?

Cc: @eneiluj

**Comment by eneiluj** [comment]
Hey, sorry, my mistake. Too many app publishing last week...

v0.0.10 is out and compatible with NC 20.
