### ISSUE TITLE
Getting stuck at "Redirecting you back to the application. This may take a few moments."

### ISSUE THREAD

**Issue by muranava** [nextcloud/integration_twitter#11]
Hi
I can't seem to connect to Twitter, I get stuck at page "Redirecting you back to the application. This may take a few moments";
i can't seem to locate any error messages associated with this in logs?

**Comment by grimneko** [comment]
Same here, I never manage to return to NC after the Twitter authorization, like the previous poster. Running NC in Docker with a Traefik reverse-proxy.

**Comment by digital-codes** [comment]
Same issue for me, return never completes. Fedora 33, Cloud 21, Firefox 88, same on chromium 89

**Comment by headkit** [comment]
same same
no redirect, no popup

**Comment by dotnetninja10** [comment]
Same error. Latest fresh nextcloud, and all other apps. Fresh install date 2021-06-28.

**Comment by eneiluj** [comment]
Twitter does not redirect to an https:// URL but rather to a custom protocol (web+nextcloudtwitter://).

To get the OAuth flow working you need to accept the custom protocol registration which is done when visiting the Connected accounts user settings section. If you're using Firefox you should see a bar on top of the page
![firefox](https://user-images.githubusercontent.com/11291457/124248067-c5de8e00-db22-11eb-93db-c876d9690cc3.png)

If you're using a Chromium based browser, you should see a popup somewhere in the top-right corner of the browser or click this icon in the address bar
![chromium](https://user-images.githubusercontent.com/11291457/124247943-a8112900-db22-11eb-8795-a78f6b26014a.png)

Once the registration is done, you can hit the "Connect to twitter" button and log in with your Twitter credentials. Then Twitter tries to visit an address starting with web+nextcloudtwitter:// which your browser should handle with a Nextcloud page.

Any better?

**Comment by headkit** [comment]
Now it worked!

**Comment by muranava** [comment]
ah right ok thanks!

**Comment by dotnetninja10** [comment]
Yes, that works, confirmed on firefox and chrome. Documentation should be updated to avoid confusion.

**Comment by eneiluj** [comment]
All I said is explained in the Connected accounts user settings. But if someone wants to add it to the README, i'll accept any PR.

Thank you all for the feedback on this issue!
