### ISSUE TITLE
No connection to Twitter Account

### ISSUE THREAD

**Issue by Stefan-11-76** [nextcloud/integration_twitter#23]
NextcloudPi V.1.38.0
Nextcloud (stable/22.1.0.1)
Twitter integration 1.0.1
RaspberryPi 4 (4GB)

![01 Twitter Einbindung](https://user-images.githubusercontent.com/85248662/129461044-5997b852-860e-4128-be68-fb3b8b141978.png)

I click Connect ...

![02 App autorisieren](https://user-images.githubusercontent.com/85248662/129461121-79e4caa1-827b-4b6c-b66e-1eedd4b3e5b5.png)

at this screen down the process stucks

![03 ewig](https://user-images.githubusercontent.com/85248662/129461145-c48118be-12ca-44bf-a8ed-b3b454f3f520.png)

**Comment by diogocardoso28** [comment]
Same issue here, see if your console also says something like this
Failed to launch 'web+nextcloudtwitter://auth-redirect?oauth_token=xxxxx&oauth_verifier=xxxxxxx' because the scheme does not have a registered handler.

**Comment by Stefan-11-76** [comment]
Can you tell me, where i can see the console message? who must i go to see the message?

**Comment by diogocardoso28** [comment]
@Stefan-11-76 F12 and then select the "console" option 
![image](https://user-images.githubusercontent.com/65686179/129573507-c812c9f0-51f9-42cc-b487-3b5e16896413.png)

**Comment by Stefan-11-76** [comment]
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). base.7ced3ee3ff61dadf91a9c9bd7082adc8f158a360.js:1:57428
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://api.twitter.com/favicon.ico blockiert ("img-src"). resource:191:19

**Comment by diogocardoso28** [comment]
You might have not accepted the browser request to open those types of link

**Comment by Stefan-11-76** [comment]
I using Ubuntu and Firefox. Firefox don't ask me for given any permission.... ?!?

**Comment by diogocardoso28** [comment]
@Stefan-11-76 That's odd, my browser asked me for permission. So not shure what's going on then, maybe try another browser.

**Comment by Stefan-11-76** [comment]
With GnomeWebbrowser i read this as error in the konsole:

Viewport argument value "device-width;" for key "width" is invalid, and has been ignored. Note that ';' is not a separator in viewport values. The list should be comma-separated.

Refused to load https://api.twitter.com/favicon.ico because it does not appear in the img-src directive of the Content Security Policy.

Same issue, no connection to Twitter over the App.

**Comment by Stefan-11-76** [comment]
with Opera it works well. There i must allow the request to twitter over the browser.

**Comment by diogocardoso28** [comment]
@Stefan-11-76 You managed to get it to work with opera ?

**Comment by Stefan-11-76** [comment]
Yes, with Opera thats working for me. Now i can view my Twitter Informations over Firefox too...
THX for conversation... :)
