### ISSUE TITLE
Changelog.md is out of date, missing the last 2 versions

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/integration_twitter#39]

**Comment by bigcat88** [comment]
will try to reflect all future changes from this time

**Comment by SimJoSt** [comment]
@bigcat88 that's awesome! Now it's even more up-to-date than the GitHub releases :)

**Comment by bigcat88** [comment]
releases are now published throw `nextcloud-releases`, so it is normal

**Comment by SimJoSt** [comment]
Sounds good, even though I don't fully understand what you mean and what `nextcloud-releases` is  :)

**Comment by bigcat88** [comment]
https://github.com/nextcloud-releases/integration_twitter
