### ISSUE TITLE
Error direct message

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_twitter#4]
With the version 0.0.3 i have this log
{"reqId":"8tDWDB1WFbBPLEbFh9Mx","level":2,"time":"2020-10-02T19:35:20+00:00","remoteAddr":"X.X.X.X","user":"X.X","app":"integration_twitter","method":"GET","url":"/apps/integration_twitter/notifications","message":"Twitter request error : Client error: `GET https://api.twitter.com/1.1/direct_messages/events/list.json?count=20` resulted in a `403 Forbidden` response","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.8"}

Must i activate App permissions
Read, Write, and Direct Messages
Read + Write + Read and post direct messages

in https://developer.twitter.com/en/portal/apps

**Comment by eneiluj** [comment]
Do you connect with your own Twitter OAuth app or are you using the default one (mine)?

In case you absolutely want to use your Twitter app (not necessary), then give it "Read + Write + Direct Messages" permissions.

The default one is used if client ID and client secret are left empty in connected account admin settings.

**Comment by eneiluj** [comment]
Any news about that? Cheers

**Comment by Ludovicis** [comment]
No more problem with default one. I will test my own twitter app later.
Thanks,

**Comment by nunesgh** [comment]
Hi @eneiluj. It is not clear in the instructions that the non-default Twitter OAuth app must have Direct Messages access. At first I didn't give my app that permission and I had no idea it was necessary for loading the Twitter notifications card on the Dashboard. I was only able to figure that out after checking the logs and finding a similar error message to the one reported by @Ludovicis.

![image](https://user-images.githubusercontent.com/16168765/96661022-85870900-1321-11eb-9d8b-856f0d77c07b.png)

**Comment by eneiluj** [comment]
@nunesgh Right thanks. I'll add it in admin settings hints.

**Comment by Ludovicis** [comment]
It's OK now with my my own twitter app thanks
