### ISSUE TITLE
Lesser Twitter Permissions

### ISSUE THREAD

**Issue by Ge0rg3** [nextcloud/integration_twitter#8]
Hi team,

I was wondering if there was a way to limit the twitter permissions given to the server for this, as by default the token has pretty much full account access (including write and delete), when only read perms are necessary?

Thanks!

**Comment by eneiluj** [comment]
Hi there,

Unfortunately, permission settings are pretty basic on twitter side and the only way to access "direct messages" is to set "Read, Write, and Direct Messages" permissions for the OAuth app. If there were more options I would certainly limit the permissions...

**Comment by Ge0rg3** [comment]
Oh right, seems like a strange choice from Twitter. Thanks for letting me know 👍
