### ISSUE TITLE
Redirecting you back to application ...

### ISSUE THREAD

**Issue by TheFoxStudio** [nextcloud/integration_twitter#9]
Hi there,

I am pretty sure I opened an issue about this in the past but it seems like all issues are gone.

I am still stuck with the same problem since the release of the integration app. I click on connect Twitter, get redirected to Twitter. Click on "authorize application" and that's it. I am stuck on the Twitter page saying "Redirecting you back to your application" and nothing happens anymore. I kept this open for hours at a time, it will not redirect.

Tested in Firefox 84.0.2 as well as in MS Edge. Caches cleared, clean logins, no ad-blocker/privacy browser extensions active.

I'd really like to get this working or at least get help where I could look for the issue.

**Comment by eneiluj** [comment]
Hi,

Sorry for not having seen your issue. Your problem is most likely that your browser does not register the `web+nextcloudtwitter` custom scheme so that when Twitter redirects you to `web+nextcloudtwitter://...`, your browser does not know what to do with such a link.

Are you by any chance accessing your Nextcloud via HTTP and not HTTPS? This could explain why the registration is not performed.

**Comment by TheFoxStudio** [comment]
Thanks for the quick response!

I did access it via HTTP but also thought this might be an issue. Testing it via HTTPS end up with the same issue.

**Comment by TheFoxStudio** [comment]
Alright! There is a fundamental misunderstanding on my side. This might be something that could be a little clearer in the instructions. The top bar saying "allow application" pops up on Nextcloud NOT on the Twitter page! That bar is the same grey as the title bar for Nextcloud and I completely missed it every single time. 

Might be just me, might be a little confusing but this is the solution for me.

I apologize for opening an issue for a user error.
Thanks for the help tho!

**Comment by eneiluj** [comment]
:grin: Don't apologize for asking questions.

I thought the screenshot was explicit enough. I'll probably add a description to that screenshot.

Glad it works for you now.
